### ISSUE TITLE
A new repo name?

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#1]
@ichoran points out:

> I think someone will need to rename the repository also, as having a bunch of people who each have their own worm trackers need to pull a repository called "worm-tracker" could generate unnecessary confusion.

Any ideas for a new name?

**Comment by Ichoran** [comment]
Maybe tracker-commons or tracker-interop?

**Comment by aexbrown** [comment]
I like tracker-commons.  Captures the spirit nicely.
Andre

On 5 Oct 2015, at 19:58, Ichoran <notifications@github.com<mailto:notifications@github.com>> wrote:

Maybe tracker-commons or tracker-interop?

**Comment by MichaelCurrie** [comment]
Done.
