### ISSUE TITLE
There should be known results to various computations on test files

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#105]
To ensure the accuracy (not just consistency) of the reading process, there should be test files where various computations produce known answers.  These should be listed somewhere so that the files can be read, the computations performed, and the answers checked against the known values.

**Comment by JimHokanson** [comment]
This would be very helpful for me.

**Comment by Ichoran** [comment]
Closing this as it is superseded by #141 which will have known answers once we define the examples.
