### ISSUE TITLE
Usage examples are minimal / missing

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#111]
There are very few examples of using the WCON reader/writers to do anything.  Every language should have a few examples.  Better yet, every language should have the _same_ examples.

Some ideas for small examples on a real data set:
- Read a data set, select IDs that last for at least 60s, write it again (with updated `software` information)
- Calculate the median length of each worm and report the 5th and 95th percentiles of those medians
- Find the fastest speed (over 1s) of any animal
- Report how many spines flip direction (head/tail)
- Produce a count of the number of worms at each second in the recording
- Generate a fake data set of a sinusoidal "worm" wiggling in place for 10s

I don't think we need all of these, but something that shows basic data extraction and writing would be valuable.

**Comment by cheelee** [comment]
I think those are great examples. And if we have the owat visualizers ready to use WCON data, that last example will be very nice. I'll go ahead and adopt a subset of those example ideas for Octave, C, and C++ once they are ready. C++ will probably be the lowest-hanging fruit.

**Comment by Ichoran** [comment]
Closing this in favor of a more extensive yet less ambitious set of possible examples in #141 (which adhere more strictly to just what WCON encodes and requires less non-WCON coding to produce a result).
