### ISSUE TITLE
WCON C/C++

### ISSUE THREAD

**Issue by cheelee** [openworm/tracker-commons#112]
After some thought, I have decided to start the creation of support for WCON-C and WCON-CPP as language interfaces in their own rights. This should be low-hanging fruit, since I have already written a version of WCON-C for the first WCON-Octave prototype.

These will be implemented as wrappers around the Python implementation, with the folder structure organized to reflect the idea that they will eventually have their own native implementations.

They can be packaged as standalone tools, and as libraries. The idea is to use the C++ library as the interface around which Octave (and Matlab) can itself be a wrapper around. The C interface will be a thin low-overhead wrapper around the C++ wrapper.

**Comment by Ichoran** [comment]
I will probably write a Rust implementation at some point also, which will either wrap the C, or the C can wrap the Rust if it gets written first.

**Comment by cheelee** [comment]
Cool! Either way, it'd be fine. Having more options won't hurt (other than from a code-maintenance point of view!) As long as one form of the implementation for each language works as advertised :)

**Comment by MichaelCurrie** [comment]
Similar to the #63 issue, we've got sufficient parsers now that this effort is not a high priority for now.  I will close this so we can maintain focus on the critical path for now.
