### ISSUE TITLE
scalar multipliers in units

### ISSUE THREAD

**Issue by JimHokanson** [openworm/tracker-commons#114]
What's the point of having scalar multipliers with units? This seems to unnecessarily complicate things. Does this automatically get applied to the data? For example, if you have a value of 1 with a unit of 0.5*s (on disk) would loading cause a value of 0.5 and a unit of 's'?

**Comment by MichaelCurrie** [comment]
> What's the point of having scalar multipliers with units? 

The rationale is discussed here: https://github.com/openworm/tracker-commons/pull/66

> Does this automatically get applied to the data? For example, if you have a value of 1 with a unit of 0.5*s (on disk) would loading cause a value of 0.5 and a unit of 's'?

Yes.

**Comment by MichaelCurrie** [comment]
Sorry I'll let you close it if you feel I've addressed your concerns.  Thanks

**Comment by JimHokanson** [comment]
Doh! I searched explicitly for an issue discussing this and missed that one. Thanks.
