### ISSUE TITLE
kilo prefix

### ISSUE THREAD

**Issue by JimHokanson** [openworm/tracker-commons#115]
In the format where it discusses units, K is  allowed for the kilo prefix. Why is this? I'd prefer it not to be ...

**Comment by MichaelCurrie** [comment]
I agree @JimHokanson; [according to SI](https://en.wikipedia.org/wiki/Kilo-):

> It has been used in the International System of Units where it has the unit symbol k, in lower case.

Happily, [the Python implementation already only allows only `k` and not `K` for kilo](https://github.com/openworm/tracker-commons/blob/master/src/Python/wcon/measurement_unit.py#L100).

It looks like we should change [the spec](https://github.com/openworm/tracker-commons/blob/master/WCON_format.md) (the schema does not need to be changed as it does not get into this much details).

**Comment by Ichoran** [comment]
The Scala implementation also only admits `k`.  I agree that it's just an error in the language of the specification--let's change it.

**Comment by MichaelCurrie** [comment]
Normally I would do a pull request but this was a two-character change so I just committed directly to master: 8cbfd4bb1ef8e572cec336a6316599cb41af6696
