### ISSUE TITLE
Scala:  sbt isn't picking up the kse package

### ISSUE THREAD

**Issue by ver228** [openworm/tracker-commons#120]
I am a beginner in Scala so I apologise if this is a very stupid question.

If I follow the instructions and execute the code from the sbt console. I got the following error:

`<console>:13: error: org.openworm.trackercommons.ReadWrite.type does not take parameters
       val worms = ReadWrite("../../tests/intermediate.wcon") match {`

I think the code must be `ReadWrite.read("../../tests/intermediate.wcon")` (I got it from the R implementation). If I use the read method, I have complains about the kse package. I have a similar problem if I run `sbt test`. I assume this is a missing package and I guess I have to clone the kse github, compile it and add it to the classpath, but is there is an easier way? I mean it seems that the `sbt package` does that for me, but I am not sure what is the correct way to load the .jar file.

**Comment by Ichoran** [comment]
You're correct that you have to use the `read` method.  I'll fix the documentation.

I am not sure why SBT isn't picking up KSE.  Maybe it's because I'm relying on snapshots and they're getting cleared?  I'll try to do a proper release.

I'm afraid it will take me a few days, though.

**Comment by Ichoran** [comment]
KSE missing is resolved by https://github.com/openworm/tracker-commons/pull/121 (for now--will break again, but I'll go to a permanent release before that happens I hope)

**Comment by Ichoran** [comment]
Missing `read` on `ReadWrite` call is fixed by https://github.com/openworm/tracker-commons/pull/122
