### ISSUE TITLE
Origin specification is complex

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#138]
Most things, like centroids, can either be there or not.  If there, they're all there (in an array).  But origins are allowed to exist as a single point that applies to all values in a time series.

This is somewhat helpful for data compaction.  But it's also a complication for implementations, especially since the data is uninterpretable, if it has origins, unless you take origins into account.

Maybe we should remove this and make origins be the same dimensionality as the time series, without exception.  (If yes, we can also simplify rules about custom JSON in the same way.)

**Comment by Ichoran** [comment]
I propose that we mandate that origins be specified in full or not at all, even if it's just the same number over and over again.  The reason is that minimal readers must handle origins, unlike custom data, so they must understand these different options.  They shouldn't have to.

**Comment by Ichoran** [comment]
The specification is simplified in #146 but software is not fully updated yet.  The Scala version was partially updated along with the perimeter implementation #136

**Comment by MichaelCurrie** [comment]
We agreed to simplify this at the meeting on 16 March.  As @Ichoran says, now it's a matter of implementing...

**Comment by Ichoran** [comment]
This is fully implemented in Scala as of #152

**Comment by MichaelCurrie** [comment]
I believe this is now handled at some point somewhat before 44df1c5
