### ISSUE TITLE
Worm ID can be a number, but this raises ambiguities

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#142]
Worm IDs are allowed to be either numbers or strings.  But what if the two are mixed?

Is `"id":0` the same as `"id":"0"`?  What about `"id":0.0`?

We should either carefully specify exactly what the equivalence is, or we should allow only string IDs (where there should be no ambiguity).

**Comment by MichaelCurrie** [comment]
I'd be in favour of allowing only string IDs.  If someone has the convention that all their worms use integer IDs, they are just as unambiguous if converted for WCON purposes into strings, so no problem there.

Using a float to identify your worms is the worst data practice I've ever heard, so let's not support that :)

**Comment by Ichoran** [comment]
Specification is updated in #146 but software is not updated yet.

**Comment by MichaelCurrie** [comment]
Tests were updated by @Ichoran with d27f2bec3ce2809c00adb2d8a67e5d1199d8dc42.

**Comment by MichaelCurrie** [comment]
It's also a rule in the schema, which is optionally used because the current schema validator used ([jsonschema](https://github.com/Julian/jsonschema/issues/277)) is very slow on large files.

Nothing else needed here; I will close this.
