### ISSUE TITLE
metadata.who - arrayed set of JSON strings (is a string allowable?)

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#143]
This is a question from @JimHokanson that may be outstanding.

**Comment by Ichoran** [comment]
The spec says, "If there is a single value, an array need not be used even if it is permitted."

So according to spec, a single string is allowable in the `"who"` field.

**Comment by Ichoran** [comment]
@JimHokanson - The question is answered by the generic wording for arrayed values.  I think the updated language in #146 may make this clearer in general, but either way I don't think we need to change this (except maybe by adding a FAQ).
