### ISSUE TITLE
License for Code

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#2]
Right now the repository is licensed under CC0, which is appropriate for public discussions, but arguably a bit less appropriate for code.

If this is to be a repository not just for discussions about common tooling for trackers, but actually for that tooling, we might want to pick a different base license, e.g. MIT or Apache.  (Or we could put that license file in a code directory, and somehow make it clear that the code isn't CC0.)

**Comment by MichaelCurrie** [comment]
Agreed, for at least three reasons:
- The rest of the OpenWorm repositories use the MIT license.
- According to the [CC0 FAQ](https://wiki.creativecommons.org/wiki/CC0_FAQ) and
  [https://creativecommons.org/weblog/entry/27081](https://creativecommons.org/weblog/entry/27081):

> One important reason why Creative Commons licenses should not be used to release software is that they aren’t compatible with existing free software licenses, most importantly the GPL from the Free Software Foundation, which is used by over half of free software projects. A commons fractured by legal incompatibilities is a weak commons
- According to the [creative commons FAQ]((https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_use_a_Creative_Commons_license_for_software.3F):

> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

So, since @aexbrown and @Ichoran are ok with MIT, I've [taken the liberty](cd9c98ec7a4158c9fcc781bab430fa1af7a7e60d) of replacing the CC0 license with the MIT one.

**Comment by Ichoran** [comment]
@MichaelCurrie - All right, I'll rebase my code reorganization on your patch, I guess?  (I'd already made the change in that PR, except it was MIT for code and CC0 for everything else.)

**Comment by MichaelCurrie** [comment]
Is there some advantage to having CC0 for non-code stuff?  If so, perhaps we should go your route.

Otherwise, if it's okay with you perhaps we could keep it simple and stick with MIT - then OpenWorm can continue to say we are MIT-licensed across the board.

**Comment by Ichoran** [comment]
The only practical advantage to CC0 that I can think of is that people who are good enough at bioinformatics to grab data but not good enough to keep track of which license is which can scrape the text without any worry about violating anything.  I'm not sure this is a very compelling "advantage".  MIT is fine with me.
