### ISSUE TITLE
Should "tracker-commons":true be first?

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#20]
According to the spec,

> **We recommend that you include the key-value pair `"tracker-commons":true` as the first entry in the WCON file to aid easy identification.** A WCON parser should not rely on the presence of this tag, so you may omit it (or not put it first) if you wish, but if the tag is present and the file is not valid WCON, a parser may choose to give more detailed error messages.

_(emphasis added)_

But according to the [JSON website](http://json.org/):

> An object is an unordered set of name/value pairs.

For this reason I'm wondering if we should even be recommending that `"tracker-commons":true` be placed "first".  The Python JSON parser parses objects into dicts, which are inherently unordered.

If we really wanted to recommend placing it first, we should wrap the outer JSON object with an array, so we can apply our desired ordering.  But I don't think that's necessary or desirable.

**Comment by Ichoran** [comment]
This is a good point; although it's permissible to respect key order, it's not required.  So maybe we shouldn't say anything about where it goes.

On the other hand, if "tracker-commons" does go first, and if units appears before data, high performance parsers could be nearly twice as fast because it would be unnecessary to parse to an intermediate format; you just get exactly what you need, or throw a parse error.  But I think we can leave that out of the spec.  It's not forbidden to pick an order you like, so those people using parsers that can work like that can save or convert their data to the order they want.

So: let's drop that requirement.  @aexbrown, do you agree?

Also, if we're doing that, should we even bother with `"tracker-commons": true` at all?

**Comment by aexbrown** [comment]
If we drop the requirement of ordering, I say we drop the "tracker-commons": true entirely.  It seems to me that potentially having to scan an entire file before you know if it's the right format is suboptimal.

**Comment by Ichoran** [comment]
Let's drop `"tracker-commons": true` entirely, then.  One can go off the extension if one needs to.  Otherwise, parse optimistically and handle errors if they arise.  (They could arise anyway.)

**Comment by MichaelCurrie** [comment]
I'm happy to go with the consensus on this, but consider:

1) At least in the Python implementation, the entire file is loaded into memory by the `json` module before any parsing takes place, so the physical position of the tracker-commons tag within the file will not slow down parsing.

2) Later parsers could distinguish between versions of WCON if the tag changes in the future, to say "tracker-commons":2, "tracker-commons":3, rather than just "tracker-commons":true.  So it could be nice to keep this tag in there.

If you think my points 1 and 2 are not valid for some reason then I agree, let's drop the tag entirely.

**Comment by Ichoran** [comment]
It's convenient but not optimal to have a generic JSON parser traverse the file.  If you've got it all in memory (especially with a schema!) there isn't much benefit to the tag.  For really huge data files, a streaming parser might be better.  For really high throughput, a parser that understands which data is supposed to be numeric arrays and parses it directly is a fair bit faster than one that parses generically and then unwraps the number-objects.  But this requires you to know what it is in advance, so if the tag isn't going to come first, you may as well just guess based on the extension.

Finally, I think we should take appropriate care to do this right the first time.  When we have a release that we call 1.0, I don't think we should ever change the format in an incompatible way.  As long as we write the spec carefully, this should be doable.  (E.g. TIFF took a few tries to get right, but TIFF 6.0 is around 20 years old and hasn't needed updates, plus extensions to it pretty much all work with the original TIFF readers even if some data is missing.)  Further, I really don't like the idea that the correctness of the data could be dependent on a single field specifying how it should be interpreted.  Robustness and obviousness are prime virtues!

So I don't think (1) and (2) are very compelling points.

**Comment by MichaelCurrie** [comment]
OK, I'll remove references to tracker-commons.  I'll create a branch to do this now.

**Comment by Ichoran** [comment]
Resolved by https://github.com/openworm/tracker-commons/pull/26
