### ISSUE TITLE
Specification for units does not match Scala implementation

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#28]
The Scala implementation insists that all units to be converted be declared up front in the "units" block (e.g. "temperature": "C"), and that metadata fields like temperature use the appropriate unit.  In contrast, the spec does not insist, and allows units to be defined in an object locally (i.e. "temperature": { "value": 20, "units": "C" }).

The reason I assumed that all units would be declared up front is that it makes it obvious at a high level if the data is going to look confusing (e.g. "x":"mm", "y":"cm" is probably a bad choice), at the expense of making it difficult to know what is going on locally in a confusing case (e.g. "cultivation": 72, "experimental": 25).  So it was mostly to encourage best practices by making it obvious if there was a problem.

However, local definition of units does allow more flexibility.  Right now, the spec is not very clear about where you might be able to locally define units.  If we're going to allow this in general (and not just have a special case for some fields of metadata), we should write a proper specification so it's clear where the tools will provide automatic conversions and where they won't.

My bias is to adopt the Scala convention (I was going off memory when I wrote it and that's what seemed to me to make the most sense).  But maybe there are considerations that I'm not properly accounting for.

**Comment by MichaelCurrie** [comment]
I agree that defining all units up front rather than also within the metadata structure is good.  It also simplified the metadata since `"temperature": { "value": 20, "units": "C" }` can be just `"temperature": 20`, since its units were already defined in the "units" object.

**Comment by Ichoran** [comment]
The only trick is that the units-converter then has to keep track of the last key that actually pertains to units instead of just taking the key for that very entry.  Because if both `"temperature": 20` and `"temperature": {"cultivation": 20, "experimental": 22}` are valid, it's rather a pain to have to specify "cultivation" and "experimental" separately in the units.

**Comment by Ichoran** [comment]
(But maybe that amount of pain is okay, given that it should be mostly handled by software.  The bigger concern is collisions between unit types if several different things have an internal "value".)

**Comment by aexbrown** [comment]
I also agree that it’s worth the pain to define units up front.

On 11 Jan 2016, at 20:45, Ichoran <notifications@github.com<mailto:notifications@github.com>> wrote:

(But maybe that amount of pain is okay, given that it should be mostly handled by software. The bigger concern is collisions between unit types if several different things have an internal "value".)

**Comment by Ichoran** [comment]
This issue is partly addressed by https://github.com/openworm/tracker-commons/pull/36 but there would still be Python, schema, and test files to fix if that is merged as it stands.

**Comment by Ichoran** [comment]
I'm going to close this to keep things more tidy--the main issue is mostly resolved (agreement on what to do + one reference implementation updated).
