### ISSUE TITLE
Metadata provides inconsistent levels of detail for cultivation vs experiment

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#33]
The WCON spec allows you to separately specify the cultivation temperature and experimental temperature.  However, although it allows you to specify media, food, and humidity overall, it does not allow you to distinguish between cultivation and experimental conditions.

This is inconsistent, and probably should be fixed before the format is publicized.
#### Option 1 -- forget the distinction

We make temperature a simple value, and rely upon people writing in the Protocol field to explain what is actually going on.  They will have to to some extent anyway for complicated setups ("25C until L4, then 15C until 3rd day of adulthood").  Downside: we no longer have access to this information programmatically.
#### Option 2 - Make each field admit cultivation/experimental specifiers

The relevant entries seem to be media, food, and humidity.  These could all look like temperature, except that media and food would be string-valued instead of floating-point-valued.
#### Option 3 - Make Arena do the extra work

We could remove the cultivation / experiment distinction from temperature and make it assumed that the values in the metadata are global.  If there is a different temperature or whatever during the experiment, we can allow those four fields to be duplicated in the arena tag (making size/shape optional).  These values would be the "experimental" ones.

**Comment by Ichoran** [comment]
@aexbrown @MichaelCurrie - What do you guys think about this?  I was writing the full Julia parser and as I was copying the metadata classes from Scala, it struck me that as it stands we don't strike a very good balance between frustrating people by allowing too many variants, and frustrating people because they can't put essential details in.

**Comment by aexbrown** [comment]
I agree the balance is currently off.  I prefer Option 1 for its simplicity and the fact that we’ll never capture complicated experimental conditions anyway.  Specific stimulus protocols for temperature etc. are best handled by custom tags because these will be very lab-specific (and potentially complicated).

**Comment by MichaelCurrie** [comment]
André makes a good point about Option 1, but I will defer to you experimentalists on this one.

Perhaps this is the sort of thing (and others we haven't thought of) that we'll be able to get feedback from the rest of the group on, when we announce WCON to them.

**Comment by Ichoran** [comment]
I'm content with any of the options, and Andre's logic sounds good to me also, so I'll make the changes in the spec and in the Scala parser.

**Comment by Ichoran** [comment]
@MichaelCurrie - After I submit a PR for the Scala and spec parts, I'll leave it to you to patch up the schema and to modify the Python reader/writer.

**Comment by Ichoran** [comment]
I'm going to close this issue to keep things moving.  I'll open a generic "need to update Python" issue instead.
