### ISSUE TITLE
Documentation examples are not guaranteed to be valid

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#34]
All examples of WCON in the documentation should be automatically pulled out and parsed during validation.  Otherwise, there is a high likelihood that the examples will drift away from actual valid WCON and will be misleading.

This requires two things:
1. All examples must be converted into complete and valid WCON
2. All examples must be automatically pulled out and parsed by a Travis CI job (or other validation).

**Comment by Ichoran** [comment]
I am taking care of (1) in my current edits of the WCON_format file.  (2) remains to be done.

**Comment by MichaelCurrie** [comment]
(2) should now be handled by [the above pull request](https://github.com/openworm/tracker-commons/pull/48).

**Comment by Ichoran** [comment]
Resolved by #48
