### ISSUE TITLE
Python should track current specification for units, age, and temperature

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#46]
I haven't been updating Python as I update the spec and Scala reference.  I also haven't been updating the example .wcon files, or the schema.  I could give it a try, but my Python skills are very rusty, and I usually make a mess of weakly-typed languages.

**Comment by MichaelCurrie** [comment]
Haven't looked at this for a couple of weeks.  Thanks for highlighting this as an issue.  I'll work on this one.

**Comment by MichaelCurrie** [comment]
This should be handled by the above pull request.

**Comment by Ichoran** [comment]
Resolved by #48
