### ISSUE TITLE
Add support for compressed (zipped) WCON files

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#59]
WCON files can be compressed 10-to-1, making them even smaller than uncompressed binary HDF5 files.  I'd like to add support so that if the parser detects the file is not text but is a compressed archive, it decompresses it before loading, and adding an option, to save the file in a compressed format.

**Comment by Ichoran** [comment]
Sure, sounds reasonable.  It should be optional, of course, for WCON readers to handle compressed format.  Zip or gz?  Both?  Can you compress a set of WCON files together in a single zip file?

**Comment by MichaelCurrie** [comment]
I read [this article](http://stackoverflow.com/questions/20762094/) to better understand the difference between all the compression formats.

Apparently they are all based on the Deflate compression method, and while `.zip` can handle multiple files, `.gz` is for single files, so first you use tar to archive multiple files then use gz, creating a `.tar.gz` file.  `.tar.gz` is best since it allows the compression algorithm to take advantage of redudancies between files, which `.zip` cannot.

However, for simplicity, I think it's probably best just to do single-file compression rather than introduce API complexity in being able to accept archives of multiple files.  With this being the case, I'd like to use the `zipfile` library in Python, which I've just studied, and therefore that would commit us to supporting at least the 'zip' format if that's okay with you, to start.

**API changes**
- The only difference to the API can be an optional boolean parameter in `.save_to_file`, `compress_file`, which I will set to default to `False`, I presume?
- For `.read_from_file`, the program should just check if the .wcon file is zipped, and uncompress before reading (but not change the file itself).

Sound good?

**Comment by Ichoran** [comment]
There already is the complexity of the format specifying a chain of files; I'm not sure that zipping them all would make it more complex.  That would be the rule: you can zip all related files together if you want.

Are we adding this as part of the extended recommendations for the specification, or just a cool thing that you can do with Python (instead of having to use the utilities and then separately zip/unzip)?  If it's just, "look at this handy trick in the Python implementation" we still want to get it right, but we don't have to think about it so much since we needn't care whether it's practical to implement in other languages.

**Comment by MichaelCurrie** [comment]
OK you convinced me to write the implementation to handle the case of zipping a chain of files:

My implementation of this unzips the archive, places it in a temporary folder, and then tries to load the first file in the archive (which should recursively add the other files in the archive if they are chained together).  Then it deletes the temporary folder.

I agree that this should be part of the "optional" spec for the implementations.  If @aexbrown and @Ichoran approve this, we can add some language to the spec.

**Comment by MichaelCurrie** [comment]
So after PR #67 was merged this is handled for the Python implementation.

**Comment by Ichoran** [comment]
Scala and Julia are still pending, so we should leave this open.

**Comment by Ichoran** [comment]
Julia zip file support: https://zipfilejl.readthedocs.org/en/latest/

Scala should probably use the ZipFileSystem stuff from Java: http://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html

Situation for Rust does not look so clear; everything is very preliminary or features are unsupported.  Best option at the moment seems to be: https://github.com/mvdnes/zip-rs

**Comment by Ichoran** [comment]
Resolved for Scala by https://github.com/openworm/tracker-commons/pull/85

Julia still outstanding

**Comment by Ichoran** [comment]
I'm going to close this as Julia isn't really fully supported.  In general, if Python and Scala have it, we can close the main feature request, I think, and have follow-up issues for other languages that we think must support the feature.
