### ISSUE TITLE
Write a Python WCON reader/writer

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#7]
@Ichoran has written a "fully self-contained" reader and writer in Scala.

Since some of the rest of the community may be more comfortable with Python, and also to demonstrate that the WCON format is not tied to I/O tools written in any one particular language, I'm writing a Python port of the parser.

I'm aiming to have this done by Monday 9 November.

**Comment by MichaelCurrie** [comment]
Starting point for Scala syntax:

http://bugra.github.io/work/notes/2014-10-18/scala-basics-for-python-developers/

Notes about Scala:
- Scala is JVM-based, so it has access to all Java libraries.
- There are many ways to do one thing, so the code can be inscrutable like Perl.

**Comment by Ichoran** [comment]
@MichaelCurrie - Note that my fully-self-contained reader/writer that I've merged only contains a minimal implementation (and doesn't handle centroids/offsets, which in hindsight I realize it must for correctness).  I'll have a maximal implementation merged on Thursday, probably.  (You can track my progress on it in my fork.)

Also, I plan on writing a Julia implementation.  If you get Python done first, I'll copy yours.  If not, the Julia syntax is probably more comfortable for Python programmers.

**Comment by Ichoran** [comment]
Note that since WCON is just JSON, an implementation can simply read the data files using any standard JSON parser, and then pull out the entries that it knows about.  Thus, one ought not have to really worry about parsing to read the file.  Output should be similarly simple as long as the JSON writer knows that NaN isn't valid JSON.  (If it will produce null, great.  If not, you have to convert any values/arrays before giving them to the JSON writer.)

**Comment by MichaelCurrie** [comment]
Still working away on this, @aexbrown - I likely won't be finished until this weekend.

**Comment by MichaelCurrie** [comment]
As it turns out to technically satisfy closing this issue would require a program just a few lines long, since as @Ichoran notes Python comes with the `json` module that can already do parsing.  In fact, there is also a `jsonschema` module for schema validation as well.  Here's how such a implementation would look:

```
import json, jsonschema

# The WCON schema
with open("wcon/wcon_schema.json", "r") as wcon_schema_file:
    schema = json.loads(wcon_schema_file.read())

# Our example WCON file
JSON_path = '../../tests/minimax.wcon'
with open(JSON_path, 'r') as infile:
    serialized_data = infile.read()

# Load the whole JSON file into a nested dict.
w = json.loads(serialized_data)

# Validate the raw file against the WCON schema
jsonschema.validate(w, schema)
```

With the above code we end up with a nested dictionary `w` containing everything that was serialized in `minimax.wcon`.

Instead, I've given the `wcon` Python package more capabilities.  I outline them [here](https://github.com/openworm/tracker-commons/blob/master/src/Python/README.md).

We can close this issue when I:
1. Get multiple files working with no errors
2. Write a "get worm in standard units" method that returns a new worm, with a new .units that are fully standard, with the data all adjusted.  This will be necessary for the data comparison method.
3. Also show an example of parsing, merging, detecting equality, etc.
   implement `__eq__` and then add more tests of that
4. Implement "Save" to WCON, (with optional chunks? that seems unnecessary)
   test subclassing the save as well.
5. Test that Worm Orientation (Head, and CW/CCW orientation) works
6. In the Python README, show an example of how to subclass and handle each type of user-defined data.  Consider showing an example of how subclassing lets you convert Shafer Lab files into WCON files, including by moving the metadata into the file.  After meeting with Jim on 19 Dec, we agreed it would be best to just subclass BasicWorm now, rather than trying to do the same for  NormalizedWorm or WormFeatures.  Hand this format off to the team at Sibernetic.  Handle custom features via subclassing: demonstrate this in your test suite, with the two kinds of custom features:
   - in "data"
   - outside of "data".

**Comment by MichaelCurrie** [comment]
Also I should note that even now you should be able to install the package on any computer via:

```
pip install wcon
```

For more detailed installation instructions visit [INSTALL.md](https://github.com/openworm/tracker-commons/tree/docs-and-WCON-equality-test/src/Python/INSTALL.md)

**Comment by MichaelCurrie** [comment]
Items 1,2,3,4,5 are handled by: https://github.com/openworm/tracker-commons/commit/42a4b1c547d16b83b721e7f9e224ef4f80ad6f50.

As for item 6, I'll do the example subclass in the movement validation repository.  I've started [an issue for that.](https://github.com/openworm/movement_validation/issues/169).

@aexbrown I believe we can close this issue now; let me know if you think otherwise.  Thanks!
