### ISSUE TITLE
In-memory representation of worms

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#73]
Currently in the Python implementation, worm data is represented as a pandas DataFrame with the rows for time frames and the columns being a MultiIndex, with columns for each skeleton point in x and y for each worm id.

This tabular representation is memory-inefficient if the worm data is "sparse", e.g. if there are multiple worms over mutually exclusive time frames.

Another representation could be a dictionary:

`worm1.data = {1:df1, 2:df2, 3,df3}`

Where 1,2,3 are the worm ids and `df1`, `df2`, `df3` are dataframes specific to those individual worms.

I've never dealt with multiworm data before so I'm getting issues with @Ichoran's worm data file which has 90 worms.  This would keep memory use down below 300 MB, whereas the current implementation uses 600-1200 MB, and more during the construction phase, which actually breaks Travis CI's 3 GB limit.

Does anyone have any thoughts or preferences here?

**Comment by Ichoran** [comment]
I strongly recommend some sort of dictionary.  You could imagine recordings that go on for days, and worms that are followed only for a few minutes.  Having vast tables of zeros isn't helping anything there.  You do want to have an index, though, so you can look up all IDs present at one timepoint.

**Comment by MichaelCurrie** [comment]
This is done now (as an ordered dictionary), with f20ac8a
