### ISSUE TITLE
Travis-CI with Octave

### ISSUE THREAD

**Issue by cheelee** [openworm/tracker-commons#74]
Am trying to see if this will work with my personal sandbox repositories before I attempt it with my fork of tracker-commons. It does look promising:

https://github.com/catch22/octave-doctest/blob/master/.travis.yml

No obvious way to do the same for Matlab as yet, however.

**Comment by Ichoran** [comment]
I think it's fine for some languages to have discontinuous integration. Mostly we won't be messing with the specification or test files (outside of this early phase while we're still working out the basics), so if the people working on the changes run tests before checking them in, and we don't have too many people working at once (so multiple merges are rare), we should be okay.

For now, if you get Octave working with Travis or Semaphore (or something else), that'd be great.

**Comment by cheelee** [comment]
Additional notes (to self) for this issue. Almost ready to move this into an in-progress task.

As a semi-standalone component of WCON, WCON-Octave has a dependency on WCON-Python. Find out if it is possible to build a CI test chain for WCON-Octave that - 
1. listens for the completion of CI tests for WCON-Python (using Travis-CI)
2. and then invokes a new CI test instance for WCON-Octave using either Travis-CI or some other CI framework tied with Github.

**Comment by Ichoran** [comment]
Can you just add it directly to the CI run for Python by adding it to the matrix somehow?  The listening and tying part sounds failure-prone.

**Comment by cheelee** [comment]
I've checked with the Travis folks a while back, the YAML file is allowed to specify exactly one language after which the CI framework is tuned to behave a certain way for that specified language. There appears to be no current way to stage and coordinate multiple language tests in the same YAML file.

Here's the discussion thread: https://github.com/travis-ci/travis-ci/issues/4090#issuecomment-217704573

**Comment by cheelee** [comment]
And you are right about the listener bit being fragile and a potential source of problems, especially in the context of a distributed code collaboration framework. I'll have to think more deeply about how it can be done with some codebase-to-test consistency guarantees.

**Comment by MichaelCurrie** [comment]
The Octave effort is superceded to a certain extent by the Matlab version, and it's already an adequate wrapper as far as I understand.  Since no further development is expected, I will mark this close.  Feel free to open this later.
