### ISSUE TITLE
Create a new release of the Python version to PyPI (1.0.0)

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#80]
List changes:
- Performance improvements (#55) (see summary of performance below)
- Changed internal representation of worms from a single DataFrame to an ordered dictionary of DataFrames, with the keys being the worm IDs.  API has not changed; `.data` is now a lazily evaluated property, while `.data_as_odict` is a property that gives direct access to the internal representation. (#73)
- Can read and write Zip files (#59)
- Units support scalar multipliers (e.g. "0.04*s" are the units for frames 1,2,3 going at 25 FPS) (#66)
- The schema for metadata allows more of what's actually allowed in the specification. (#53)

**Python performance summary**

File used for test: `tracker-commons/tests/from_schafer_lab.wcon`
Size: 59.3 MB (4641 frames, ~ 250 points x and 250 points y per frame)
Zipped size: 5.57 MB

| Instruction | Time (seconds) | `jsonschema.validate` used? | Cores used |
| --- | --- | --- | --- |
| WCONWorms.load_from_file | 1.00 | No | 1 |
| WCONWorms.load_from_file | 74.29 | Yes | 1 |
| WCONWorms.save_to_file | 5.38 | n/a | 1 |

**Comment by MichaelCurrie** [comment]
Just as soon as #79 is accepted.

**Comment by Ichoran** [comment]
Just merged #79 since I think it's probably okay and I had a spare second now, but if the tests fail you should patch that up first!

**Comment by MichaelCurrie** [comment]
Thanks!  I appreciate the promptness.  Looks like they passed.

**Comment by MichaelCurrie** [comment]
Done: 

https://github.com/openworm/tracker-commons/releases/tag/v1.0.0 and

https://pypi.python.org/pypi/wcon/1.0.0
