### ISSUE TITLE
Detailed setup instructions broken for fresh Ubuntu 14.04 LTS install via Virtualbox

### ISSUE THREAD

**Issue by cheelee** [openworm/tracker-commons#81]
### Broken Steps:
1. sudo pip install wcon - results in:

File "wcon/wcon_parser.py", line 21, in <module> 

  import jsonschema

ImportError: No module named jsonschema 
1. Attempting to fix this with sudo pip install jsonschema - results in:

File "wcon/wcon_parser.py", line 25, in <module>

  idx = pd.IndexSlice

AttributeError: 'module' object has no attribute 'IndexSlice' 
### Weirdness Issues:
1. numpy installed twice ... once through pip, another through apt-get.
2. the long apt-get line installs a ton of stuff as dependencies, including TexLive. Are the dependencies for what we need actually minimal?
### Alternative Success:

I have had success (i.e. was able to run python tests.py and get 23 successes) using a git clone with Miniconda3, and with the following environment dependency file for python3 (environment.yml). Have not tested against python 2 for Ubuntu yet, but I had done something similar on Mac OS X and it worked for python 2 (and fails for python 3 because something about psutil appeared to be broken on Mac OS X):

```
name: wcon3
dependencies:
  - python=3.*
  - scipy
  - pandas
  - jsonschema
  - psutil
```

**Comment by MichaelCurrie** [comment]
`AttributeError: 'module' object has no attribute 'IndexSlice'` is the error you get if your pandas is out of date.

Great point about the `INSTALL.md` not handling this or the `jsonschema` install.  I will now try to work out a clean Miniconda3 set of install steps (probably mirroring what the `.travis.yml` is doing).

**Comment by MichaelCurrie** [comment]
OK I have updated (and tested from scratch!) the new install instructions.  Thanks for pushing me on this, I appreciate it.

Commits 9b5bad85702f4385f16c62b94d524256911c69b4 and 91db15263bfed2e18c5b7ebb4347b426d578ada6.
