### ISSUE TITLE
Possible Bug with __add__ operation in Python, with multiple worms

### ISSUE THREAD

**Issue by cheelee** [openworm/tracker-commons#87]
I was expecting x = y + z where y and z are different but compatible to produce an x which is different from both y and z. Instead the following code produced the following results:

x = y + z results in x == y
x = z + y results in x == z

https://gist.github.com/cheelee/e3cc3b513f605a46bebbd49136b78e78

**Comment by MichaelCurrie** [comment]
Fixed with 8c44302f446bd0cf3a110316ce967ee1cad06d1c.

Thanks for finding this, @cheelee!
