### ISSUE TITLE
R implementation is missing

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#98]
R is heavily used in biostatistics and big data analysis.  An R implementation would enable access to a huge range of statistical tools, and also to a substantial number of people who have expertise in R but not other programming languages.

The implementation strategy should almost certainly be based around the R-Scala interface package rscala.  The way we should use it is documented at https://darrenjw.wordpress.com/2015/08/15/calling-scala-code-from-r-using-rscala/

**Comment by cheelee** [comment]
That sounds great! Especially with a good Scala implementation now!

**Comment by Ichoran** [comment]
Resolved by https://github.com/openworm/tracker-commons/pull/109

Not very well, but kinda.
